version: "3.8"
services:
  db:
    image: postgres:12.4-alpine
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    # Comment this volume section to spin up a new database every time you run docker-compose up
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: jobhopper_dev

  api:
    build:
      context: ../api
      dockerfile: docker/Dockerfile
    image: jobhoper-api
    volumes:
      - ../api:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: jobhopper_dev
      DB_HOST: db
      WAIT_HOSTS: db:5432

  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    image: jobhopper-frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    stdin_open: true

volumes:
  db-data:
